inherit_gem:
  rubocop-govuk:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'lib/export_tables_to_big_query.rb'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/data.rake'

Rake/Desc:
  Enabled: false
