inherit_from: .rubocop_todo.yml
AllCops:
    TargetRubyVersion: 2.4
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'db/seeds.rb'
      - 'bin/**/*'
      - 'config/initializers/simple_form.rb'

Rails:
    Enabled: true

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingBlankLines:
    Enabled: false

Style/TrailingCommaInLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:
      - 'spec/**/*'

Metrics/AbcSize:
    Max: 20
    Exclude:
      - 'spec/**/*'
Metrics/ModuleLength:
    Exclude:
      - 'spec/support/vacancy_helpers.rb'

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Max: 40
    Exclude:
      - 'spec/**/*'
