inherit_from: .rubocop_todo.yml
AllCops:
    TargetRubyVersion: 2.4
    Exclude:
      - 'db/migrate/**/*'
      - 'db/schema.rb'
      - 'bin/**/*'
      - 'config/initializers/simple_form.rb'

Rails:
    Enabled: true

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingBlankLines:
    Enabled: false

Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 10
    Exclude:
      - 'spec/**/*'

Metrics/LineLength:
    Max: 120

Metrics/BlockLength:
    Exclude:
      - 'spec/**/*'

