inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'lib/export_tables_to_big_query.rb'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/data.rake'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: false
