inherit_gem:
  rubocop-govuk:
    - config/default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/TrailingEmptyLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'lib/export_tables_to_big_query.rb'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/data.rake'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Rake/Desc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  Enabled: false
