version: '3.6'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '54320:5432'
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:alpine
  web:
    build:
      context: .
      target: dev-build
    image: teaching-vacancies
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DATABASE_URL: 'postgres://postgres:password@db:5432/tvs_development?template=template0&pool=5&encoding=unicode'
      REDIS_QUEUE_URL: 'redis://redis:6379'
      REDIS_CACHE_URL: 'redis://redis:6379'
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
  sidekiq:
    image: teaching-vacancies
    environment:
      RAILS_ENV: development
      DATABASE_URL: 'postgres://postgres:password@db:5432/tvs_development?template=template0&pool=5&encoding=unicode'
      REDIS_QUEUE_URL: 'redis://redis:6379'
      REDIS_CACHE_URL: 'redis://redis:6379'
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    command: /bin/sh -c "bundle exec sidekiq -C config/sidekiq.yml"
volumes:
  pgdata:
