version: '3.1'
services:
  test: &test
    build:
      context: .
      args:
        RAILS_ENV: "test"
    environment:
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://postgres@db-test:5432"
    container_name: teacher-vacancy-service_test_1
    env_file:
      - docker-compose.env
    volumes:
      - .:/srv/dfe-tvs:cached
      - node_modules:/srv/dfe-tvs/node_modules:cached
    depends_on:
      - db-test
    command: ["bundle", "exec", "./bin/dsetup && spring server"]
    restart: on-failure
    networks:
      - tests

  db-test:
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    image: postgres:9.6-alpine
    volumes:
      - pg_test_data:/var/lib/postgresql/data/:cached
    networks:
      - tests
    ports:
      - "25432:5432"
    restart: on-failure

networks:
  tests:

volumes:
  pg_test_data: {}
  node_modules:
