---
AUTHENTICATION_FALLBACK: false
BIG_QUERY_DATASET: production_dataset
DFE_SIGN_IN_ISSUER: https://oidc.signin.education.gov.uk
DFE_SIGN_IN_REDIRECT_URL: https://teaching-vacancies.service.gov.uk/auth/dfe/callback
DFE_SIGN_IN_URL: https://api.signin.education.gov.uk
DISABLE_EXPENSIVE_JOBS: false
DOMAIN: teaching-vacancies.service.gov.uk
FEATURE_JOBSEEKER_ACCOUNTS: false
FEATURE_JOBSEEKER_APPLICATIONS: false
FEATURE_LOCAL_AUTHORITY_ACCESS: true
FEATURE_READ_ONLY: false
GOOGLE_ANALYTICS_PROFILE_ID: ga:171744074
OPENSSL_CONF: /etc/ssl/
RACK_ENV: production
RAILS_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
ROLLBAR_ENV: production
SKYLIGHT_ENABLED: true
SKYLIGHT_ENV: production
SKYLIGHT_IGNORED_ENDPOINTS: ApplicationController#check
