---
AUTHENTICATION_FALLBACK: false
BIG_QUERY_DATASET: production_dataset
CLOUD_STORAGE_BUCKET: tvs_production
DISABLE_EXPENSIVE_JOBS: false
DOMAIN: teaching-vacancies.service.gov.uk
FEATURE_EMAIL_ALERTS: true
FEATURE_MULTI_SCHOOL_JOBS: false
FEATURE_READ_ONLY: false
FEATURE_SCHOOL_GROUP_JOBS: false
GOOGLE_ANALYTICS_PROFILE_ID: ga:171744074
GOOGLE_CLOUD_PLATFORM_PROJECT_ID: teacher-vacancy-service
OPENSSL_CONF: /etc/ssl/
RACK_ENV: production
RAILS_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
ROLLBAR_ENV: production
SKYLIGHT_ENABLED: true
SKYLIGHT_ENV: production
SKYLIGHT_IGNORED_ENDPOINTS: ApplicationController#check
