# Example file

# Basic auth
HTTP_USER: user
HTTP_PASS: password

# External dependencies
DATABASE_URL: postgres://postgres@localhost:5432/tvs_development?template=template0&pool=5&encoding=unicode

# Integrations
GOOGLE_MAPS_API_KEY: '123'
