default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://postgres@localhost:5432') %>
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS') { 5 }) %>

development:
  <<: *default
  database: tvs_development

test:
  <<: *default
  database: tvs_test

staging:
  <<: *default

production:
  <<: *default
