default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: dfe-beta_development

test:
  <<: *default
  database: dfe-beta_test

production:
  url: <%= ENV['DATABASE_URL'] %>
