default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS') { 5 }) %>

development:
  <<: *default
  database: tvs_development

test:
  <<: *default
  database: tvs_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
