:queues:
  - [ daily_alert_email, 1 ]
  - [ mailers, 3 ]
  - [ page_view_collector, 2 ]
  - [ performance_platform, 2 ]
  - [ google_indexing, 2]
  - [ import_school_data, 1 ]
  - [ update_vacancy_spreadsheet, 1 ]
  - [ audit_published_vacancy, 1 ]
  - [ audit_express_interest_event, 1 ]
  - [ audit_search_event, 1 ]
  - [ audit_feedback, 1 ]
  - [ audit_spreadsheet, 1 ]
update_vacancy_spreadsheet:
  :concurrency: 1
audit_published_vacancy:
  :concurrency: 1
audit_express_interest_event:
  :concurrency: 1
audit_search_event:
  :concurrency: 1
audit_feedback:
  :concurrency: 1
audit_spreadsheet:
  :concurrency: 1
audit_toc_acceptance_event:
  :concurrency: 1
mailers:
  :concurrency: 2
