:max_retries: 5

:queues:
  - [high, 4]
  - [default, 2]
  - [low, 1]
  # TODO: Remove all below once no more jobs in queues in production
  - [email_alerts, 4]
  - [mailers, 3]
  - [queue_daily_alerts, 3]
  - [queue_weekly_alerts, 3]
  - [google_indexing, 2]
  - [performance_platform, 2]
  - [vacancy_statistics, 2]
  - [audit_express_interest_event, 1]
  - [audit_general_feedback, 1]
  - [audit_published_vacancy, 1]
  - [audit_search_event, 1]
  - [audit_subscription_creation, 1]
  - [audit_vacancies, 1]
  - [audit_vacancy_publish_feedback, 1]
  - [clear_emergency_login_keys, 1]
  - [email_feedback_prompt, 1]
  - [export_tables, 1]
  - [export_users, 1]
  - [import_polygon_data, 1]
  - [import_school_data, 1]
  - [import_trust_data, 1]
  - [refresh_cached_vacancy_statistics, 1]
  - [refresh_vacancy_facets, 1]
  - [remove_invalid_subscriptions, 1]
  - [remove_stale_vacancies, 1]
  - [remove_vacancies_that_expired_yesterday, 1]
  - [reset_sessions, 1]
  - [seed_vacancies_from_api, 1]
  - [send_event_to_data_warehouse, 1]
  - [submit_performance_platform, 1]
  - [update_algolia_index, 1]
  - [update_dsi_users_in_db, 1]
mailers:
  :concurrency: 2
seed_vacancies_from_api:
  :concurrency: 2
audit_express_interest_event:
  :concurrency: 1
audit_general_feedback:
  :concurrency: 1
audit_published_vacancy:
  :concurrency: 1
audit_search_event:
  :concurrency: 1
audit_subscription_creation:
  :concurrency: 1
audit_vacancies:
  :concurrency: 1
audit_vacancy_publish_feedback:
  :concurrency: 1
clear_emergency_login_keys:
  :concurrency: 1
export_tables:
  :concurrency: 1
export_users:
  :concurrency: 1
refresh_cached_vacancy_statistics:
  :concurrency: 1
refresh_vacancy_facets:
  :concurrency: 1
remove_invalid_subscriptions:
  :concurrency: 1
remove_stale_vacancies:
  :concurrency: 1
remove_vacancies_that_expired_yesterday:
  :concurrency: 1
reset_sessions:
  :concurrency: 1
submit_performance_platform:
  :concurrency: 1
update_algolia_index:
  :concurrency: 1
update_dsi_users_in_db:
  :concurrency: 1
