name: Deploy

on:
  push:
    branches:
      - dev
      - staging
    paths-ignore:
    - 'bigquery/**'
    - 'documentation/**'
    - 'terraform/common/**'
    - 'terraform/monitoring/**'

env:
 DOCKERHUB_REPOSITORY: dfedigital/teaching-vacancies

jobs:
  turnstyle:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: softprops/turnstyle@v1
      name: Check workflow concurrency
      with:
        poll-interval-seconds: 20
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: build docker image and deploy
    needs: turnstyle
    runs-on: ubuntu-20.04
    outputs:
      BRANCH: ${{ steps.set_env_vars.outputs.BRANCH }}
      TAG: ${{ steps.set_env_vars.outputs.TAG }}
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Pin Terraform version
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_version: 0.13.4

    - name: Set environment variables
      id: set_env_vars
      run: |
        BRANCH=$(echo ${GITHUB_REF} | cut -d/ -f3)
        TAG=${BRANCH}-${GITHUB_SHA}-$(date '+%Y%m%d%H%M%S')
        echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
        echo "TAG=${TAG}" >> $GITHUB_ENV
        echo ::set-output name=BRANCH::${BRANCH}
        echo ::set-output name=TAG::${TAG}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Validate secrets
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2
      run: |
        gem install aws-sdk-ssm --no-document
        bin/run-in-env -t "/tvs/${BRANCH}" -o quiet \
          && echo Data in "/tvs/${BRANCH}" looks valid

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image from builder target
      uses: docker/build-push-action@v2
      with:
        build-args: BUILDKIT_INLINE_CACHE=1
        cache-from: |
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-master
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
        push: true
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
        target: builder

    - name: Build and push docker image from production target
      uses: docker/build-push-action@v2
      with:
        build-args: BUILDKIT_INLINE_CACHE=1
        cache-from: |
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-master
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH }}
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TAG }}
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH }}
        target: production

    - name: Trigger Deploy App Workflow for branch
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        workflow: Deploy App to Environment # Workflow name
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{"environment": "${ env.BRANCH }", "tag": "${ env.TAG }"}'

    - name: Wait for Deploy App Workflow
      id: wait_for_deploy_app
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        checkName: Deploy app to environment # Job name within workflow
        ref: ${{ github.ref }}
        timeoutSeconds: 300
        intervalSeconds: 15

    - name: Send success message to twd_tv_dev channel
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2.1.1
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':tada:'
        SLACK_TITLE: Deployment success
        SLACK_MESSAGE: 'Deployment of Docker tag ${{ steps.set_env_vars.outputs.TAG }} to ${{ steps.set_env_vars.outputs.BRANCH }} - successful :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send failure message to twd_tv_dev channel
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.1
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':cry:'
        SLACK_TITLE: Deployment failure
        SLACK_MESSAGE: 'Deployment of Docker tag ${{ steps.set_env_vars.outputs.TAG }} to ${{ steps.set_env_vars.outputs.BRANCH }} - failure'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
