name: Review

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

env:
  CF_PROVIDER_VERSION: 0.12.4
  DOCKERHUB_REPOSITORY: dfedigital/teaching-vacancies
  PR_NAME: ${{ format('pr-{0}', github.event.number) }}

jobs:
  turnstyle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: softprops/turnstyle@v1
      name: Check workflow concurrency
      with:
        poll-interval-seconds: 20
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Create review app
    needs: turnstyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Validate secrets
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        gem install aws-sdk-ssm --no-document
        bin/run-in-env -t /tvs/dev -o quiet \
          && echo Data in /tvs/dev looks valid

    - name: Terraform pin version
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.1

    - name: Set environment variables
      id: set_env_vars
      run: |
        TAG=review-${PR_NAME}-${GITHUB_SHA}-$(date '+%Y%m%d%H%M%S')
        echo ::set-env name=TAG::${TAG}
        echo ::set-env name=DOCKER_BUILDKIT::1

    - name: Build and push docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKERHUB_REPOSITORY }}
        tags: ${{ env.TAG }}
        target: production

    - name: Terraform deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_paas_user: ${{ secrets.CF_USERNAME }}
        TF_VAR_paas_password: ${{ secrets.CF_PASSWORD }}
      run: |
        export TF_VAR_paas_app_docker_image=${DOCKERHUB_REPOSITORY}:${TAG}
        export TF_VAR_environment=review-${PR_NAME}
        terraform init -input=false -backend-config="workspace_key_prefix=review:" terraform/app
        terraform workspace select review-${PR_NAME} terraform/app || terraform workspace new review-${PR_NAME} terraform/app
        terraform apply -var-file terraform/workspace-variables/review.tfvars -auto-approve -input=false terraform/app

    - name: Post PR comment
      if: ${{ success() }}
      run: |
        curl --header "Accept: application/vnd.github.v3+json" \
             --header "Authorization: Bearer ${{ github.token }}" \
             --request POST \
             --data '{"body": "Review app deployed to https://teaching-vacancies-review-${{ format('pr-{0}', github.event.number) }}.london.cloudapps.digital"}' \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments

    - name: Send success message to twd_tv_dev channel
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':tada:'
        SLACK_TITLE: Deployment success
        SLACK_MESSAGE: 'Review app for PR ${{ github.event.number }} deployed to https://teaching-vacancies-review-${{ env.PR_NAME }}.london.cloudapps.digital :rocket:'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send failure message to twd_tv_dev channel
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':cry:'
        SLACK_TITLE: Deployment failure
        SLACK_MESSAGE: 'Review app deployment failed for PR ${{ github.event.number }}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
