name: Review

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]
    paths-ignore:
    - 'bigquery/**'
    - 'documentation/**'
    - 'terraform/common/**'
    - 'terraform/monitoring/**'

env:
  DOCKERHUB_REPOSITORY: dfedigital/teaching-vacancies

jobs:
  turnstyle:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - uses: softprops/turnstyle@v1
      name: Check workflow concurrency
      with:
        poll-interval-seconds: 20
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Create review app
    needs: turnstyle
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Validate secrets
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2
      run: |
        gem install aws-sdk-ssm --no-document
        bin/run-in-env -t /teaching-vacancies/dev -o quiet \
          && echo Data in /teaching-vacancies/dev looks valid

    - name: Terraform pin version
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: 0.13.4

    - name: Set environment variables
      id: set_env_vars
      run: |
        $(echo "BRANCH=${{ github.head_ref }}" | sed -e 's/\//_/g' >> $GITHUB_ENV)
        TAG=review-pr-${{ github.event.number }}-${{ github.sha }}-$(date '+%Y%m%d%H%M%S')
        echo "TAG=${TAG}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image from builder target
      uses: docker/build-push-action@v2
      with:
        build-args: BUILDKIT_INLINE_CACHE=1
        cache-from: |
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-master
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
        push: true
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
        target: builder

    - name: Build and push docker image from production target
      uses: docker/build-push-action@v2
      with:
        build-args: BUILDKIT_INLINE_CACHE=1
        cache-from: |
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-master
          ${{ env.DOCKERHUB_REPOSITORY }}:builder-${{ env.BRANCH }}
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH }}
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.TAG }}
          ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.BRANCH }}
        target: production

    - name: Trigger Deploy App Workflow for review
      uses: benc-uk/workflow-dispatch@v1.1
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}
        workflow: Deploy App to Environment # Workflow name
        inputs: '{"environment": "review-pr-${{ github.event.number }}", "tag": "${{ env.TAG }}"}'

    - name: Wait for Deploy App Workflow
      id: wait_for_deploy_app
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
        checkName: Deploy app to environment # Job name within workflow
        timeoutSeconds: 300
        intervalSeconds: 15

    - name: Post PR comment
      if: ${{ steps.wait_for_deploy_app.outputs.conclusion == 'success' }}
      run: |
        curl --header "Accept: application/vnd.github.v3+json" \
             --header "Authorization: Bearer ${{ github.token }}" \
             --request POST \
             --data '{"body": "Review app deployed to https://teaching-vacancies-review-pr-${{ github.event.number }}.london.cloudapps.digital"}' \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments

    - name: Send job status message to twd_tv_dev channel
      uses: rtCamp/action-slack-notify@v2.1.1
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_TITLE: Deployment ${{ job.status }}
        SLACK_MESSAGE: 'Review app for PR ${{ github.event.number }} deployed to https://teaching-vacancies-review-pr-${{ github.event.number }}.london.cloudapps.digital - ${{ job.status }}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
