name: Smoke Test Manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
      sha:
        description: 'GitHub SHA'
        required: true

jobs:
  smoke-test-manual-job:
    name: Smoke Test ${{ github.event.inputs.sha }} on ${{ github.event.inputs.environment }}

    runs-on: ubuntu-20.04

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Run smoke test
        run: bundle exec rspec spec/smoke_tests/jobseekers_can_view_homepage_${{ github.event.inputs.environment }}_spec.rb --tag smoke_test

      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_CHANNEL: twd_tv_dev
          SLACK_USERNAME: Smoke Test
          SLACK_ICON_EMOJI: ':cry:'
          SLACK_TITLE: Smoke test failed
          SLACK_MESSAGE: 'Smoke Test ${{ github.event.inputs.sha }} on ${{ github.event.inputs.environment }} has failed !channel'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
