name: Smoke Test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      sha:
        description: GitHub SHA
        required: true
      smoke_test_domain:
        description: Domain to smoke test
        required: true
        default: teaching-vacancies.service.gov.uk

jobs:
  smoke-test:
    name: Smoke Test ${{ github.event.inputs.smoke_test_domain }} ${{ github.event.inputs.sha }}

    runs-on: ubuntu-20.04

    env:
      RAILS_ENV: test
      SMOKE_TEST_DOMAIN: ${{ github.event.inputs.smoke_test_domain }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - name: Run smoke test
        run: bundle exec rspec spec/smoke_tests/jobseekers_can_view_homepage_spec.rb --tag smoke_test

      - name: Slack notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.2
        env:
          SLACK_CHANNEL: twd_tv_dev
          SLACK_USERNAME: Smoke Test
          SLACK_ICON_EMOJI: ':cry:'
          SLACK_TITLE: Smoke test failed
          SLACK_MESSAGE: 'Smoke test failure ${{ github.event.inputs.smoke_test_domain }} <!channel>'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
