name: Smoke Test

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  smoke-test:
    name: Run production website smoke test

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Set up ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 20 --retry 3

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run smoke test
        run: bundle exec rspec spec/smoke_test/ --tag smoke_test

      - name: Slack notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: twd_tv_dev
          SLACK_USERNAME: Smoke Test
          SLACK_TITLE: Smoke test failed
          SLACK_MESSAGE: 'Production website smoke test has failed :cry: @channel'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
