name: Sync staging database

on:
  schedule:
  # The schedule is in UTC and uses cron syntax
  # * is a special character in YAML so you have to quote this string
  - cron: '0 2 * * *'

jobs:
  sync:
    name: Sync staging database from production
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CF client
      uses: DFE-Digital/github-actions/install-cf-cli@master

    - name: Install postgres client
      uses: DFE-Digital/github-actions/install-postgres-client@master

    - name: Dump production database to file
      env:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
        CF_SERVICE_NAME: teaching-vacancies
        CF_SOURCE_ENVIRONMENT: production
      run: bin/dump-db

    - name: Restore staging database from dump
      env:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
        CF_SERVICE_NAME: teaching-vacancies
        CF_DESTINATION_ENVIRONMENT: staging
      run: bin/restore-db

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Upload backup to S3
      run: bin/upload-db-backup

    - name: Send success message to twd_tv_dev channel
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_TITLE: DB syncing success
        SLACK_MESSAGE: 'Successful db backup and sync production->staging'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send failure message to twd_tv_dev channel
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: twd_tv_dev
        SLACK_USERNAME: CI Deployment
        SLACK_ICON_EMOJI: ':cry:'
        SLACK_TITLE: DB syncing failure
        SLACK_MESSAGE: 'Failed db backup and sync production->staging'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
